name: Backend

on:
  pull_request:
  push:
    branches:
      - master
      - 'feature**'
      - 'release**'
      - 'ci**'
    tags:
      - '**'

jobs:

  be-linter-bikeshed:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Prepare JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Get M2 cache
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/project.clj') }}
    - run: lein with-profile +include-all-drivers,+cloverage,+junit,+oss deps
    - run: lein with-profile +ci,+oss bikeshed

  be-linter-eastwood:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Prepare JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Get M2 cache
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/project.clj') }}
    - run: lein with-profile +include-all-drivers,+cloverage,+junit,+oss deps
    - name: Run Eastwood
      run: |
        set -o pipefail
        lein with-profile +ci,+oss eastwood | tee eastwood.log
    - name: Convert linter output to annotation
      run: ./bin/convert2annotations.js eastwood.log eastwood-annotations.json
      if: always()
    - name: Upload GitHub annotations
      uses: yuzutech/annotations-action@v0.1.0
      if: always()
      with:
        input: './eastwood-annotations.json'
        repo-token: "${{ secrets.GITHUB_TOKEN }}"

  be-linter-docstring-checker:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Prepare JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Get M2 cache
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/project.clj') }}
    - run: lein with-profile +include-all-drivers,+cloverage,+junit,+oss deps
    - run: lein with-profile +ci,+oss docstring-checker

  be-linter-namespace-decls:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Prepare JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Get M2 cache
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/project.clj') }}
    - run: lein with-profile +include-all-drivers,+cloverage,+junit,+oss deps
    - run: lein with-profile +ci,+oss check-namespace-decls

  be-linter-reflection-warnings:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Prepare JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Get M2 cache
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/project.clj') }}
    - run: lein with-profile +include-all-drivers,+cloverage,+junit,+oss deps
    - run: ./bin/reflection-linter
      name: Run reflection warnings checker

  be-linter-cloverage:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Prepare JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Get M2 cache
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/project.clj') }}
    - run: lein with-profile +include-all-drivers,+cloverage,+junit,+oss deps
    - run: lein with-profile +ci,+oss cloverage --codecov

