name: Docker

on:
  push:
  pull_request:
    paths:
    - '**/Dockerfile'

jobs:

  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v2
    - name: Build container image
      run: docker build -t test-container-image .
