name: Foobar

on:
  pull_request:
  push:
    branches:
      - master
      - 'release**'
      - 'feature**'
      - 'fix**'
      - 'ci**'
    tags:
      - '**'
    paths:
    - 'frontend/**'
    - 'enterprise/frontend/**'
    - 'docs/**'
    - '**/package.lock'
    - '**/yarn.lock'
    - '.github/workflows/**'

jobs:

  foobar-eslint:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: Prepare Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Get yarn cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
    - run: yarn install --frozen-lockfile --prefer-offline
    - run: yarn run lint-eslint
      name: Run ESLint linter