name: i18n

on: [push, pull_request]

jobs:

  verify-i18n-files:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Prepare Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Get yarn cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
    - run: yarn install --lockfile

    - run: sudo apt install gettext

    - run: ./bin/i18n/update-translation-template
      name: Check i18n tags/make sure template can be built
    - run: ./bin/i18n/build-translation-resources
      name: Verify i18n translations (.po files)
